---
- hosts: all
  remote_user: ubuntu
  tasks:
  - name: Copy file from control node to managed node with owner and permissions
    copy:
      src: files/scratch.json
      dest: /home/ubuntu/scratch.json
      owner: ubuntu
      group: ubuntu
      mode: preserve
  - name: create a cloudformation stack
    cloudformation:
      stack_name: "sun-cft"
      state: "present"
      region: "us-east-1"
      disable_rollback: true
      template: "/home/ubuntu/scratch.json"
      template_parameters:
        NotebookInstanceName: "scholar-notes"
        NotebookInstanceType: "ml.t2.medium"
        SageMakerRoleArn: "arn:aws:iam::130159455024:role/service-role/AmazonSageMaker-ExecutionRole-20171220T151680"
      tags:
        Stack: "ansible-CFT-stack"
      notification_arns: "arn:aws:sns:us-east-1:130159455024:Sunlife_Notifier_SNS"
    register: result
  - name: testing with debug
    debug: 
      var: result
  - name: Iff stack is complete then trigger email microservice
    uri: 
        body_format: json
        force_basic_auth: true
        method: POST
        return_content: true
        src: files/email_body.json
        url: "http://54.224.130.193:5000/email"
    when: result['output'] == "Stack CREATE complete"
     
     
        
        
        
        
        
