---
- hosts: all
  remote_user: ubuntu
  tasks:
    - name: calling the email microervice    
      uri:
        url : http://52.91.234.13:5000/email
        method : POST
        body_format: json
        src : files/email_body.json
        force_basic_auth: yes
        return_content: yes
        
        
        
        
        
        
        
        
        
        
