--- 
- 
  hosts: localhost
  remote_user: ubuntu
  tasks: 
    - 
      name: "calling the email microervice"
      uri: 
        body_format: json
        force_basic_auth: true
        method: POST
        return_content: true
        src: files/email_body.json
        url: "http://52.91.234.13:5000/email"
