---
- hosts: localhost
  name: "deploys a cloud formation stack which creates a Sagemaker Execution IAM Role"
  vars:
    slf_notebook_execution_role_template_url: "https://slf-ces-cloudformations-repo.s3.ca-central-1.amazonaws.com/sagemaker/slf_aws_sagemaker_notebook_execution_role_template.yaml"
    stack_name_prefix: slf-aws-edtadmin-sagemaker-iam-execution
    access_type: "{{request_variable_access_to_prod}}"
  tasks:
    - name: Get RoleType,RoleID and stack_name when user requests for a personal notebook
      set_fact:
        RoleType : personal
        RoleID : "{{ request_variable_requested_for_acf2 }}"
        stack_name : "{{ stack_name_prefix }}-personal-{{ request_variable_requested_for_acf2 }}"
      when: access_type == "Personal Workspace"

    - name: Get RoleType,RoleID and stack_name when user requests for a project notebook
      set_fact:
        RoleType : project
        RoleID : "{{project_code }}" # ? mappiing key i.e, project_code = csanalytics
        stack_name : "{{ stack_name_prefix }}-{{project_code}}"
      when: access_type != "Personal Workspace"

    - name: create a Sagemaker execution IAM role stack for slf_aws_sagemaker_notebook
      cloudformation:
        stack_name: "{{ stack_name }}"
        state: "present"
        region: "{{ region }}"
        disable_rollback: true
        template: "{{ template_path }}"
        #template_url: "{{ slf_notebook_execution_role_template_url }}"
        template_parameters:
          RoleType: "{{ RoleType }}"
          RoleID: "{{ RoleID }}"
          CostCentre: "{{ request_variable_cost_centre_personal_or_project }}"
          GovtClearance: "{{ GovtClearance }}"
        tags:
          Stack: "{{ stack_name }}"
      register: IAM_exec_role_cft_output

    - name: printing the captured return result from execution of above task
      debug:
        var: IAM_exec_role_cft_output

    - name: writing registered cft output into a file
      copy:
        content: "{{ IAM_exec_role_cft_output }}"
        dest: Logs/{{ stack_name }}-logs.log





personal:

ansible-playbook -e '{"request_variable_access_to_prod":"Personal Workspace","request_variable_requested_for_acf2":"q225","region":"ca-central-1","request_variable_cost_centre_personal_or_project":"Cost-Centre","GovtClearance":"false","template_path":"./q_slf_IAM_exec_cft.yaml"}'  playbook_iam_exec.yaml

project:

ansible-playbook -e '{"request_variable_access_to_prod":"Project Workspace","project_code":"csanalytics","region":"ca-central-1","request_variable_cost_centre_personal_or_project":"Cost-Centre","GovtClearance":"false","template_path":"./q_slf_IAM_exec_cft.yaml"}' playbook_iam_exec.yaml






